displayName=Farming Guild Overview
author=wouterrutgers
description=Display the status of all patches in the Farming Guild. This provides a quick overview of what needs to be pre-planted.
tags=farming,contracts,patches
plugins=com.farmingguildoverview.FarmingGuildOverviewPlugin
version=1.0.0
build=standard
